DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS counter;

CREATE TABLE item (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	topic TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	completed TEXT NOT NULL
);


CREATE TABLE counter (
	id INTEGER PRIMARY KEY,
	completed INTEGER NOT NULL
);

INSERT INTO counter (id, completed)
VALUES (1, 0)




